# Generated by Django 4.1.2 on 2024-06-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_on_tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password2',
        ),
    ]
