# Generated by Django 4.1.2 on 2024-06-28 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_on_tour', '0002_remove_client_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(max_length=100)),
                ('nivel_curso', models.CharField(max_length=100)),
                ('cantidad_alumnos', models.IntegerField()),
                ('servicio', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_viaje', models.CharField(max_length=100)),
                ('monto_depositado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta_monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_on_tour.client')),
            ],
        ),
    ]
