# Generated by Django 4.1.2 on 2024-06-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_on_tour', '0004_alter_curso_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_viaje',
            field=models.DateField(),
        ),
    ]
