# Generated by Django 4.1.2 on 2024-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_on_tour', '0005_alter_curso_fecha_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='meta_monto',
            field=models.IntegerField(),
        ),
    ]
