# Generated by Django 4.1.2 on 2024-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_on_tour', '0006_alter_curso_meta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='monto_depositado',
            field=models.IntegerField(),
        ),
    ]
